apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: log-generator
spec:
  replicas: 1
  revisionHistoryLimit: 5
  strategy:
   type: RollingUpdate
   rollingUpdate:
    maxSurge: 2 
    maxUnavailable: 0 
  template:
    metadata:
      labels:
        app: log-generator
    spec:
      containers:
      - name: log-generator
        image: busybox
        args: [/bin/sh, -c,
                'i=0; while true; do echo "$i: $(date) test-task"; i=$((i+1)); sleep 2; done']